### PR TITLE
Remove sold items

### PR DESCRIPTION
**Pull request by jaco-99**
This PR implement the feature requested on issue #21.

If a product is sold it will not be added to the list and if it is already present it will be removed.

### CODE REVIEW

**Comment by morrolinux** [comment]
Why is this closed?
I haven't had the time to review it.

**Comment by jaco-99** [comment]
My bad, I was trying to remove the third commit which adds something that has nothing to do with this PR. I mistakenly pushed it yesterday. In short, it just adds some formatting to Telegram messages.

**Comment by morrolinux** [comment]
Can you remove the last commit and force push maybe?

**Comment by jaco-99** [comment]
Removed.

**Comment by morrolinux** [comment]
Thanks!

**Pull request merged**
